### ISSUE TITLE
Add repository to travis and coveralls 

### ISSUE THREAD

**Issue by tchellomello** [Aftermath/neos#7]
Add repository to travis and coveralls. 
- How to enable travis -> https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

- How to enable coveralls -> https://github.com/integrations/coveralls

@Aftermath  the repository is already configured, but you need to enable it on your github account.

**Comment by Aftermath** [comment]
Working on it.

**Comment by Aftermath** [comment]
I _think_ we are all set here.

RST for the coveralls badge:
```
.. image:: https://coveralls.io/repos/github/Aftermath/neos/badge.svg?branch=master
:target: https://coveralls.io/github/Aftermath/neos?branch=master
```
And for Travis-CI:
```
.. image:: https://travis-ci.org/Aftermath/neos.svg?branch=master
    :target: https://travis-ci.org/Aftermath/neos
```
